name: Update Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  update-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate snake
        run: |
          python snake.py > snake.txt

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
